name: CI

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
    - name: Configure PostgreSQL
      uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '13'
        postgresql db: 'postgres'
        postgresql user: 'postgres'
        postgresql password: 'S3cret!'

    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure Scala
      uses: olafurpg/setup-scala@v10
      with:
        java-version: "graalvm-ce-java11@20.2.0"

    - name: Coursier cache
      uses: coursier/cache-action@v5

    - name: Build and Test
      run: |
        sbt -v -Dfile.encoding=UTF-8 +test
        rm -rf "$HOME/.ivy2/local" || true
        find $HOME/Library/Caches/Coursier/v1 -name "ivydata-*.properties" -delete || true
        find $HOME/.ivy2/cache                -name "ivydata-*.properties" -delete || true
        find $HOME/.cache/coursier/v1         -name "ivydata-*.properties" -delete || true
        find $HOME/.sbt                       -name "*.lock"               -delete || true
      shell: bash
