name: CI

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
    - name: Configure Services (DB)
      uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '13'
        postgresql db: 'postgres'
        postgresql user: 'postgres'
        postgresql password: 'S3cret!'

    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure Scala
      uses: olafurpg/setup-scala@v10
      with:
        java-version: "graalvm-ce-java11@20.0.2"

    - name: Build and Test
      run: sbt -v -Dfile.encoding=UTF-8 +test
      shell: bash
